############ PACOTES ############3
library(simmer)
library(queueing)
library(ggplot2)
library(parallel)
library(simmer.plot)
library(dplyr)
set.seed(2412)

##Dados do sistema
####Coraçãoer
lambda.Brasil<-142.394
mu.Brasil <- 143
#Criando o sistema do SUS 
internação<-trajectory()%>%seize("Tratamento",amount=1)%>%timeout(function() rexp(1,mu.Brasil))%>%release("Tratamento",amount=1) 
SUS_c<-simmer("SUS_c")%>%add_resource("Tratamento",capacity=1,queue_size=Ind)%>%add_generator(("Tratamento"),internação, function() rexp(1, lambda.Brasil))%>%run(until=20) 
Recursos <- get_mon_resources(SUS_c)
png(filename="/home/alexandre/Documentos/Processo estocastico/coração_utilização.png")
plot(Recursos, metric = "utilization")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/coração_server.png")
plot(Recursos, metric = "usage", items = "server")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/coração_usage-server.png")
plot(get_mon_resources(SUS_c), metric = "usage", items = "server", steps = TRUE)
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/coração_usage-queue.png")
plot(get_mon_resources(SUS_c), metric = "usage", items = c("server","queue"), steps = TRUE)
dev.off()
chegadas <- get_mon_arrivals(SUS_c)
png(filename="/home/alexandre/Documentos/Processo estocastico/coração_tempo.png")
plot(chegadas, metric = "flow_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/coração_atividade-tempo.png")
plot(chegadas, metric = "activity_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/coração_espera-tempo.png")
plot(chegadas, metric = "waiting_time", c("tratamento"))
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/coração_utilização-recursos.png")
plot(SUS_c, what = "resources", metric = "usage", items = "system",steps = TRUE)
dev.off() 
##Simulação teorica 
mm1=NewInput.MM1(lambda=lambda.Brasil,mu=mu.Brasil,n=234)
modelo=QueueingModel(mm1)
names(modelo)
a=summary(modelo)
### resultado normal 
####Cornea
lambda.Brasil<-3682.8
mu.Brasil <- 3683
#Criando o sistema do SUS 
internação<-trajectory()%>%seize("Tratamento",amount=1)%>%timeout(function() rexp(1,mu.Brasil))%>%release("Tratamento",amount=1) 
SUS_cor<-simmer("SUS_cor")%>%add_resource("Tratamento",capacity=1,queue_size=Inf)%>%add_generator(("Tratamento"),internação, function() rexp(1, lambda.Brasil))%>%run(until=20) 
Recursos <- get_mon_resources(SUS_cor)
png(filename="/home/alexandre/Documentos/Processo estocastico/Cornea_utilização.png")
plot(Recursos, metric = "utilization")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Cornea_usage.png")
plot(Recursos, metric = "usage", items = "server")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Cornea_usage-server.png")
plot(get_mon_resources(SUS_cor), metric = "usage", items = "server", steps = TRUE)
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Cornea_Server-queue.png")
plot(get_mon_resources(SUS_cor), metric = "usage", items = c("server","queue"), steps = TRUE)
dev.off()
chegadas <- get_mon_arrivals(SUS_cor)
png(filename="/home/alexandre/Documentos/Processo estocastico/Cornea_flow-time.png")
plot(chegadas, metric = "flow_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Cornea_activity.png")
plot(chegadas, metric = "activity_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Cornea_waiting.png")
plot(chegadas, metric = "waiting_time", c("Transplante"))
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Cornea_system.png")
plot(SUS_cor, what = "resources", metric = "usage", items = "system",steps = TRUE)
dev.off()
##Simulação teorica 
mm1=NewInput.MM1(lambda=lambda.Brasil,mu=mu.Brasil,n=22871)
modelo=QueueingModel(mm1)
names(modelo)
summary(modelo)
#### Resultado 
####Figado
lambda.Brasil<-608.887
mu.Brasil <- 609
#Criando o sistema do SUS 
internação<-trajectory()%>%seize("Tratamento",amount=1)%>%timeout(function() rexp(1,mu.Brasil))%>%release("Tratamento",amount=1) 
SUS_fig<-simmer("SUS_fig")%>%add_resource("Tratamento",capacity=1,queue_size=Inf)%>%add_generator(("Tratamento"),internação, function() rexp(1, lambda.Brasil))%>%run(until=20) 
Recursos <- get_mon_resources(SUS_fig)
png(filename="/home/alexandre/Documentos/Processo estocastico/Figado_utilização.png")
plot(Recursos, metric = "utilization")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Figado_usage.png")
plot(Recursos, metric = "usage", items = "server")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Figado_usage-server.png")
plot(get_mon_resources(SUS_fig), metric = "usage", items = "server", steps = TRUE)
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Figado_usage-queue.png")
plot(get_mon_resources(SUS_fig), metric = "usage", items = c("server","queue"), steps = TRUE)
dev.off()
chegadas <- get_mon_arrivals(SUS_fig)
png(filename="/home/alexandre/Documentos/Processo estocastico/Figado_flow.png")
plot(chegadas, metric = "flow_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Figado_activity.png")
plot(chegadas, metric = "activity_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Figado_activity.png")
plot(chegadas, metric = "waiting_time", c("tratamento"))
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Figado_system.png")
plot(SUS_fig, what = "resources", metric = "usage", items = "system",steps = TRUE)
dev.off()
mm1=NewInput.MM1(lambda=lambda.Brasil,mu=mu.Brasil,n=5367)
modelo=QueueingModel(mm1)
names(modelo)
a=summary(modelo)
#### Resultado 
####Pulmão
lambda.Brasil<-27.717
mu.Brasil <- 28
#Criando o sistema do SUS 
internação<-trajectory()%>%seize("Tratamento",amount=1)%>%timeout(function() rexp(1,mu.Brasil))%>%release("Tratamento",amount=1) 
SUS_pul<-simmer("SUS_pul")%>%add_resource("Tratamento",capacity=1,queue_size=Inf)%>%add_generator(("Tratamento"),internação, function() rexp(1, lambda.Brasil))%>%run(until=20) 
Recursos <- get_mon_resources(SUS_pul)
png(filename="/home/alexandre/Documentos/Processo estocastico/Pulmão_utilization.png")
plot(Recursos, metric = "utilization")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Pulmão_sever.png")
plot(Recursos, metric = "usage", items = "server")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Pulmão_usage-sever.png")
plot(get_mon_resources(SUS_pul), metric = "usage", items = "server", steps = TRUE)
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Pulmão_sever-queue.png")
plot(get_mon_resources(SUS_pul), metric = "usage", items = c("server","queue"), steps = TRUE)
dev.off()
chegadas <- get_mon_arrivals(SUS_pul)
png(filename="/home/alexandre/Documentos/Processo estocastico/Pulmão_flow.png")
plot(chegadas, metric = "flow_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Pulmão_activity.png")
plot(chegadas, metric = "activity_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Pulmão_waiting.png")
plot(chegadas, metric = "waiting_time", c("tratamento"))
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Pulmão_system.png")
plot(SUS_pul, what = "resources", metric = "usage", items = "system",steps = TRUE)
dev.off()
mm1=NewInput.MM1(lambda=lambda.Brasil,mu=mu.Brasil,n=97)
modelo=QueueingModel(mm1)
names(modelo)
a=summary(modelo)
##### Resultado
##Rim
lambda.Brasil<-2718.91
mu.Brasil <- 2719
#Criando o sistema do SUS 
internação<-trajectory()%>%seize("Tratamento",amount=1)%>%timeout(function() rexp(1,mu.Brasil))%>%release("Tratamento",amount=1) 
SUS_rim<-simmer("SUS_rim")%>%add_resource("Tratamento",capacity=1,queue_size=Inf)%>%add_generator(("Tratamento"),internação, function() rexp(1, lambda.Brasil))%>%run(until=20) 
Recursos <- get_mon_resources(SUS_rim)
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_utilization.png")
plot(Recursos, metric = "utilization")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_usage.png")
plot(Recursos, metric = "usage", items = "server")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_usage-sever.png")
plot(get_mon_resources(SUS_rim), metric = "usage", items = "server", steps = TRUE)
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_sever-queue.png")
plot(get_mon_resources(SUS_rim), metric = "usage", items = c("server","queue"), steps = TRUE)
dev.off()
chegadas <- get_mon_arrivals(SUS_rim)
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_flow.png")
plot(chegadas, metric = "flow_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_activity.png")
plot(chegadas, metric = "activity_time")
dev,off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_waiting.png")
plot(chegadas, metric = "waiting_time", c("tratamento"))
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_system.png")
plot(SUS_rim, what = "resources", metric = "usage", items = "system",steps = TRUE)
dev.off()
mm1=NewInput.MM1(lambda=lambda.Brasil,mu=mu.Brasil,n=30047)
modelo=QueueingModel(mm1)
names(modelo)
a=summary(modelo)

##pancreas
lambda.Brasil<-2718.91
mu.Brasil <- 2719
#Criando o sistema do SUS 
internação<-trajectory()%>%seize("Tratamento",amount=1)%>%timeout(function() rexp(1,mu.Brasil))%>%release("Tratamento",amount=1) 
SUS_rim<-simmer("SUS_rim")%>%add_resource("Tratamento",capacity=1,queue_size=30047)%>%add_generator(("Tratamento"),internação, function() rexp(1, lambda.Brasil))%>%run(until=20) 
Recursos <- get_mon_resources(SUS_rim)
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_utilization.png")
plot(Recursos, metric = "utilization")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_usage.png")
plot(Recursos, metric = "usage", items = "server")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_usage-sever.png")
plot(get_mon_resources(SUS_rim), metric = "usage", items = "server", steps = TRUE)
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_sever-queue.png")
plot(get_mon_resources(SUS_rim), metric = "usage", items = c("server","queue"), steps = TRUE)
dev.off()
chegadas <- get_mon_arrivals(SUS_rim)
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_flow.png")
plot(chegadas, metric = "flow_time")
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_activity.png")
plot(chegadas, metric = "activity_time")
dev,off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_waiting.png")
plot(chegadas, metric = "waiting_time", c("tratamento"))
dev.off()
png(filename="/home/alexandre/Documentos/Processo estocastico/Rim_system.png")
plot(SUS_rim, what = "resources", metric = "usage", items = "system",steps = TRUE)
dev.off()
mm1=NewInput.MM1(lambda=lambda.Brasil,mu=mu.Brasil,n=30047)
modelo=QueueingModel(mm1)
names(modelo)
a=summary(modelo)





